spring:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
---
spring:
  config:
    activate:
      on-profile: dbtest
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE # mysql처럼 사용하기
    username: SA
    password: